const fontFamilies = [
  { name: 'Dela Gothic One', style: '"Dela Gothic One", cursive' },
  { name: 'DotGothic16', style: '"DotGothic16", sans-serif' },
  { name: 'Hachi Maru Pop', style: '"Hachi Maru Pop", cursive' },
  { name: 'Hina Mincho', style: '"Hina Mincho", serif' },
  { name: 'Kaisei Decol', style: '"Kaisei Decol", serif' },
  { name: 'Kaisei HarunoUmi', style: '"Kaisei HarunoUmi", serif' },
  { name: 'Kaisei Opti', style: '"Kaisei Opti", serif' },
  { name: 'Kaisei Tokumin', style: '"Kaisei Tokumin", serif' },
  { name: 'Kiwi Maru', style: '"Kiwi Maru", serif' },
  { name: 'Klee One', style: '"Klee One", cursive' },
  { name: 'Kosugi', style: '"Kosugi", sans-serif' },
  { name: 'Kosugi MaruP', style: '"Kosugi Maru", sans-serif' },
  { name: 'Mochiy Pop One', style: '"Mochiy Pop One", sans-serif' },
  { name: 'Mochiy Pop P One', style: '"Mochiy Pop P One", sans-serif' },
  { name: 'Murecho', style: '"Murecho", sans-serif' },
  { name: 'New Tegomin', style: '"New Tegomin", serif' },
  { name: 'Noto Sans JPP', style: '"Noto Sans JP", sans-serif' },
  { name: 'Noto Serif JP', style: '"Noto Serif JP", serif' },
  { name: 'Noto Serif JP', style: '"Potta One", cursive' },
  { name: 'Potta One', style: '"Rampart One", cursive' },
  { name: 'Reggae One', style: '"Reggae One", cursive' },
  { name: 'RocknRoll One', style: '"RocknRoll One", sans-serif' },
  { name: 'Sawarabi Gothic', style: '"Sawarabi Gothic", sans-serif' },
  { name: 'Sawarabi Mincho', style: '"Sawarabi Mincho", sans-serif' },
  { name: 'Shippori Antique', style: '"Shippori Antique", sans-serif' },
  { name: 'Shippori Antique B1', style: '"Shippori Antique B1", sans-serif' },
  { name: 'Shippori Mincho', style: '"Shippori Mincho", serif' },
  { name: 'Shippori Mincho B1', style: '"Shippori Mincho B1", serif' },
  { name: 'Stick', style: '"Stick", sans-serif' },
  { name: 'Train One', style: '"Train One", cursive' },
  { name: 'Yomogi', style: '"Yomogi", cursive' },
  { name: 'Yuji Boku', style: '"Yuji Boku", serif' },
  { name: 'Yuji Mai', style: '"Yuji Mai", serif' },
  { name: 'Yuji Syuku', style: '"Yuji Syuku", serif' },
  { name: 'Yusei Magic', style: '"Yusei Magic", sans-serif' },
  { name: 'Zen Antique', style: '"Zen Antique", serif' },
  { name: 'Zen Antique Soft', style: '"Zen Antique Soft", serif' },
  { name: 'Zen Kaku Gothic Antique', style: '"Zen Kaku Gothic Antique", sans-serif' },
  { name: 'Zen Kaku Gothic New', style: '"Zen Kaku Gothic New", sans-serif' },
  { name: 'Zen Kurenaido', style: '"Zen Kurenaido", sans-serif' },
  { name: 'Zen Maru Gothic', style: '"Zen Maru Gothic", sans-serif' },
  { name: 'Zen Old Mincho', style: '"Zen Old Mincho", serif' },
];
export default fontFamilies;
